;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        markdown-exdent-or-delete
        org-beginning-of-line
        org-self-insert-command
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        delete-line-no-kill
        yaml-electric-backspace
        ))
